const breadcrumbNameMap = {
  "/hospitalFinancial":"医院财务报表",
  "/hospitalFinancial/outpatientBillingFee": "门诊开单费用统计",
  "/hospitalFinancial/paymentOfOutpatient": "门诊挂账统计",
  "/hospitalFinancial/advancePaymentPatient": "预交款病人明细",
  "/hospitalFinancial/dischargePatientDepartment": "出院病人病区科室汇总",
  "/hospitalFinancial/hospitalPatientLedger": "在院病人总账报表",
  "/drugQuery":"药品查询",
  "/drugQuery/dugDeliveryAndStorage":"药品收发存表",
  "/drugQuery/pharmacyPayments":"药库收支月报",
  "/drugQuery/drugInventory":"药品库存查询",
  "/personalManagement":"人事管理",
  "/personalManagement/personnelQuery":"人事管理查询",
  "/generalAffairsManagement":"总务管理",
  "/generalAffairsManagement/departmentOfRecipients":"科室领用分析",
  "/generalAffairsManagement/warehouseInventory":"库房库存分析",
  "/generalAffairsManagement/equipmentList":"在用设备清单",
  "/medicalBusiness":"医疗业务统计",
  "/medicalBusiness/outpatientEmergencyFlow":"门急诊流量分析",
  "/medicalBusiness/outpatientRegistration":"门急诊挂号分析",
  "/medicalBusiness/outpatientEmergencyPhysician":"门急诊医师工作量统计",
  "/medicalBusiness/outpatientEmergencyBusiness":"门急诊业务状况分析",
  "/medicalBusiness/outpatientEmergencyIllness":"门急诊疾病统计分析",
  "/medicalBusiness/medicalLaboratory":"医技科室工作量统计",
  "/medicalBusiness/surgicalDepartmentWorkload":"手术科室工作量统计",
  "/medicalBusiness/distributionPatients":"在院病人分布状况",
  "/medicalBusiness/distributionDisease":"在院疾病分布状况",
  "/medicalBusiness/criticalPatients":"在院危急病人清单",
  "/medicalBusiness/dischargeDeath":"出院死亡病人清单",
  "/medicalBusiness/diseaseHospital":"出院疾病统计分析",
  "/medicalBusiness/bedUsing":"床位使用状况分析",
  "/patientManagement":"病人管理",
  "/patientManagement/checkInpatientInformation":"查询住院病人资料",
  "/communicableDiseasesControl":"传染病管理",
  "/communicableDiseasesControl/query":"传染病统计查询",
  "/slowDiseaseManagement":"慢病管理",
  "/slowDiseaseManagement/query":"慢病统计查询",
  "/criticalPatients":"危重病人管理",
  "/criticalPatients/query":"危重病人统计查询",
  "/telemedicine":"远程医疗",
  "/telemedicine/query":"远程医疗统计查询",
  "/dualReferral":"双向转诊",
  "/dualReferral/query":"双向转诊统计查询",
  "/statementManagement":"报表管理",
  "/statementManagement/query":"报表管理统计查询"
};
export default breadcrumbNameMap;
